const data = [
    {
      id: 1,
      bulan: "January",
      namaBarang: "Larry the Bird",
      persediaan: "@mdo",
      kuantiti: "@mdo",
      sisaStock: "@mdo",
      harga: "@mdo",
      tanggal: "@mdo",
      detail: {
        namaBarang: "Jacob",
        persediaan: "Thornton",
        kuantiti: "@fat",
        sisaStock: "@fat",
        harga: "@fat",
        tanggal: "@fat",
      },
    },
    {
      id: 2,
      bulan: "February",
      namaBarang: "Larry the Bird",
      persediaan: "@mdo",
      kuantiti: "@mdo",
      sisaStock: "@mdo",
      harga: "@mdo",
      tanggal: "@mdo",
      detail: {
        namaBarang: "Jacob",
        persediaan: "Thornton",
        kuantiti: "@fat",
        sisaStock: "@fat",
        harga: "@fat",
        tanggal: "@fat",
      },
    },
    {
      id: 2,
      bulan: "February",
      namaBarang: "Larry the Bird",
      persediaan: "@mdo",
      kuantiti: "@mdo",
      sisaStock: "@mdo",
      harga: "@mdo",
      tanggal: "@mdo",
      detail: {
        namaBarang: "Jacob",
        persediaan: "Thornton",
        kuantiti: "@fat",
        sisaStock: "@fat",
        harga: "@fat",
        tanggal: "@fat",
      },
    },
    {
      id: 2,
      bulan: "February",
      namaBarang: "Larry the Bird",
      persediaan: "@mdo",
      kuantiti: "@mdo",
      sisaStock: "@mdo",
      harga: "@mdo",
      tanggal: "@mdo",
      detail: {
        namaBarang: "Jacob",
        persediaan: "Thornton",
        kuantiti: "@fat",
        sisaStock: "@fat",
        harga: "@fat",
        tanggal: "@fat",
      },
    },
    {
      id: 2,
      bulan: "February",
      namaBarang: "Larry the Bird",
      persediaan: "@mdo",
      kuantiti: "@mdo",
      sisaStock: "@mdo",
      harga: "@mdo",
      tanggal: "@mdo",
      detail: {
        namaBarang: "Jacob",
        persediaan: "Thornton",
        kuantiti: "@fat",
        sisaStock: "@fat",
        harga: "@fat",
        tanggal: "@fat",
      },
    },
  ];

  export default data